### ISSUE TITLE
When will the new versions of data be released?

### ISSUE THREAD

**Issue by DRSY** [tianyi-lab/Reflection_Tuning#2]
Thanks for the great work!

I have tried version 1 of the data, it is definitely of high-quality. Just wondering when will the new versions of data be released.

Best regards!

**Comment by MingLiiii** [comment]
Hi, thank you very much for your interest and appreciation~ 
We will release the V2 data in one week or two. The V2 uses a different method, so we are still working hard to finish the draft V2 paper. 

Sorry about that!
