### ISSUE TITLE
Model Training Code

### ISSUE THREAD

**Issue by yqy2001** [tianyi-lab/Reflection_Tuning#5]
Hi there! Thank you for the great work.

Would you release the code for training and evaluating models trained on your datasets?

Thanks.

**Comment by MingLiiii** [comment]
Thank you for your interest!
We directly utilize the [FastChat (Vicuna)](https://github.com/lm-sys/FastChat) code for training. The input template is also aligned with FastChat (Vicuna).
Our trained models are provided in `Data and Model Weights V1` and `Data and Model Weights V2` of the Readme.

**Comment by yqy2001** [comment]
Got it. Thank you!
